# Generated by Django 4.2.6 on 2023-10-11 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 11, 12, 59, 42, 899348, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
