# Generated by Django 4.2.6 on 2023-10-11 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_alter_messages_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messages",
            name="time",
        ),
        migrations.AddField(
            model_name="messages",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 11, 13, 0, 5, 301049, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
