# Generated by Django 4.2.6 on 2023-10-25 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0003_remove_messages_time_messages_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="messaging.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="messages",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 25, 15, 25, 32, 730162, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
